---
driver:
  name: ec2
  aws_ssh_key_id: chef_demo_2x
  region: us-west-2
  security_group_ids: sg-2560a741
  associate_public_ip: true
  instance_type: t2.micro
  tags:
    # Replace YOURNAME and YOURCOMPANY here
    Name: "Chef Training Node for <YOURNAME>, Rees"
    created-by: "test-kitchen"
    user: Administrator
    X-Contact: "Anthony Rees"
    X-Application: "Training"
    X-Dept: "Solutions Architects"
    X-Customer: "Test-Kitchen"
    X-Project: "Test-Kitchen"
    X-TTL: 4

provisioner:
  name: chef_zero

verifier:
  name: inspec
  format: documentation

platforms:
  - name: centos-6
    transport:
      username: centos
      ssh_key:  ~\.ssh\id_rsa
    driver_config:
      user_data: C:/Users/chef/user_data

suites:
  - name: default
    run_list:
      - recipe[webserver::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
